version: "3.8"

services:
  db:
    image: postgres:17
    container_name: bomchefe-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    volumes:
      - ./:/app
    container_name: bomchefe-api
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:

