version: "3.8"

services:
  # Serviço do Banco de Dados (sem alterações)
  db:
    image: postgres:17
    container_name: bomchefe-db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço da API Backend (FastAPI)
  api:
    build: .
    volumes:
      # --- CORREÇÃO APLICADA AQUI ---
      # Mapeia o diretório raiz do projeto (.), criando a estrutura de pastas correta
      # dentro do contêiner para que o Python encontre o módulo 'app'.
      - ./:/app
    container_name: bomchefe-api
    restart: always
    depends_on:
      - db
    env_file: .env

  # Serviço do Front-end (Angular + Nginx)
  frontend:
    build: ./app-frontend/biscoitos-bom-chefe
    container_name: bomchefe-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:

# version: "3.8"

# services:
#   db:
#     image: postgres:17
#     container_name: bomchefe-db
#     restart: always
#     env_file: .env
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   api:
#     build: .
#     volumes:
#       - ./:/app
#     container_name: bomchefe-api
#     restart: always
#     depends_on:
#       - db
#     env_file: .env
#     ports:
#       - "8000:8000"

# volumes:
#   postgres_data:

