"""Create tables

Revision ID: 16db4336abc7
Revises: e4a9d553dda8
Create Date: 2025-06-04 01:48:43.400248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16db4336abc7'
down_revision: Union[str, None] = 'e4a9d553dda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_venda', sa.Column('quantidade', sa.Integer(), nullable=False))
    op.add_column('itens_venda', sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('itens_venda', 'preco_unitario_registrado')
    op.drop_column('itens_venda', 'quantidade_vendida')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_venda', sa.Column('quantidade_vendida', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('itens_venda', sa.Column('preco_unitario_registrado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('itens_venda', 'preco_unitario')
    op.drop_column('itens_venda', 'quantidade')
    # ### end Alembic commands ###
