"""Create tables

Revision ID: 4eaf90473442
Revises: 
Create Date: 2025-06-07 14:53:44.155490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eaf90473442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('venda_consolidada', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_estoque_venda_consolidada'), 'estoque', ['venda_consolidada'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estoque_venda_consolidada'), table_name='estoque')
    op.drop_column('estoque', 'venda_consolidada')
    # ### end Alembic commands ###
