"""Create tables

Revision ID: 8d89c59206ef
Revises: 4a3d2b4cb1ab
Create Date: 2025-06-01 17:38:55.756778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d89c59206ef'
down_revision: Union[str, None] = '4a3d2b4cb1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feiras', sa.Column('data', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_feiras_nome'), table_name='feiras')
    op.create_index(op.f('ix_feiras_nome'), 'feiras', ['nome'], unique=False)
    op.create_index(op.f('ix_feiras_data'), 'feiras', ['data'], unique=False)
    op.add_column('vendas', sa.Column('feira_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vendas_feira_id'), 'vendas', ['feira_id'], unique=False)
    op.create_foreign_key(None, 'vendas', 'feiras', ['feira_id'], ['feira_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_index(op.f('ix_vendas_feira_id'), table_name='vendas')
    op.drop_column('vendas', 'feira_id')
    op.drop_index(op.f('ix_feiras_data'), table_name='feiras')
    op.drop_index(op.f('ix_feiras_nome'), table_name='feiras')
    op.create_index(op.f('ix_feiras_nome'), 'feiras', ['nome'], unique=True)
    op.drop_column('feiras', 'data')
    # ### end Alembic commands ###
