"""Create tables

Revision ID: b5396792fe38
Revises: 4cc83e40891f
Create Date: 2025-06-01 20:32:56.420914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5396792fe38'
down_revision: Union[str, None] = '4cc83e40891f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('feira_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estoque', 'feiras', ['feira_id'], ['feira_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estoque', type_='foreignkey')
    op.drop_column('estoque', 'feira_id')
    # ### end Alembic commands ###
