"""Create produtos table

Revision ID: e192d0dbbfb5
Revises: d3b268c94b37
Create Date: 2025-04-19 23:29:31.443669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e192d0dbbfb5'
down_revision: Union[str, None] = 'd3b268c94b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    op.drop_index('ix_clientes_cliente_id', table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo_pessoa', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('documento', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cliente_id', name='clientes_pkey'),
    sa.UniqueConstraint('documento', name='clientes_documento_key')
    )
    op.create_index('ix_clientes_cliente_id', 'clientes', ['cliente_id'], unique=False)
    op.create_table('produtos',
    sa.Column('id_produto', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('estoque_atual', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('estoque_atual >= 0', name='check_estoque_positivo'),
    sa.CheckConstraint('preco >= 0::numeric', name='check_preco_positivo'),
    sa.PrimaryKeyConstraint('id_produto', name='produtos_pkey')
    )
    # ### end Alembic commands ###
